name = "fashion-brand-matcher"
compatibility_date = "2024-01-15"

# Cloudflare Pages configuration
[env.production]
account_id = ""
route = ""

# Build configuration for Cloudflare Pages
[build]
command = "npm run build"
publish = "dist"

# Environment variables
[env.production.vars]
NODE_ENV = "production"